//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorMixer.Contracts.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ColorMixer.Contracts.Localization.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        internal static string add_color_set {
            get {
                return ResourceManager.GetString("add_color_set", resourceCulture);
            }
        }
        
        internal static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        internal static string save_set {
            get {
                return ResourceManager.GetString("save_set", resourceCulture);
            }
        }
        
        internal static string mixing_type {
            get {
                return ResourceManager.GetString("mixing_type", resourceCulture);
            }
        }
        
        internal static string mixing_addictive {
            get {
                return ResourceManager.GetString("mixing_addictive", resourceCulture);
            }
        }
        
        internal static string mixing_subtractive {
            get {
                return ResourceManager.GetString("mixing_subtractive", resourceCulture);
            }
        }
        
        internal static string mixing_average {
            get {
                return ResourceManager.GetString("mixing_average", resourceCulture);
            }
        }
        
        internal static string rgb_red {
            get {
                return ResourceManager.GetString("rgb_red", resourceCulture);
            }
        }
        
        internal static string rgb_blue {
            get {
                return ResourceManager.GetString("rgb_blue", resourceCulture);
            }
        }
        
        internal static string rgb_green {
            get {
                return ResourceManager.GetString("rgb_green", resourceCulture);
            }
        }
        
        internal static string setting_sync_os {
            get {
                return ResourceManager.GetString("setting_sync_os", resourceCulture);
            }
        }
        
        internal static string setting_selected_theme {
            get {
                return ResourceManager.GetString("setting_selected_theme", resourceCulture);
            }
        }
        
        internal static string setting_dark_mode {
            get {
                return ResourceManager.GetString("setting_dark_mode", resourceCulture);
            }
        }
        
        internal static string setting_high_contrast {
            get {
                return ResourceManager.GetString("setting_high_contrast", resourceCulture);
            }
        }
        
        internal static string setting_selected_ui_culture {
            get {
                return ResourceManager.GetString("setting_selected_ui_culture", resourceCulture);
            }
        }
    }
}
